# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: shellexec@0
  inputs:
    code: |
      git config --global user.email "$(gitmailid)"
      git config --global user.name "$(gitusername)"
      git checkout qa
      
      git pull https://$(gitusername):$(gitpassword)@github.com/rameshbalidi/wordpress dev
      
      git merge dev
      
      git push https://$(gitusername):$(gitpassword)@github.com/rameshbalidi/wordpress qa

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-wordpress-stage'
    runOptions: 'commands'
    commands: 'sudo chmod -R 777 /var/www/html/'
    readyTimeout: '20000'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh-wordpress-stage'
    sourceFolder: '/home/vsts/work/1/s/'
    contents: '!**/.git/**'
    targetFolder: '/var/www/html/'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-wordpress-stage'
    runOptions: 'commands'
    commands: 'sudo bash /home/ec2-user/database.sh'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-wordpress-stage'
    runOptions: 'commands'
    commands: 'sudo chmod -R 755 /var/www/html/'
    readyTimeout: '20000'